In [1]:
from pathlib import Path

from clearml import Dataset
import pandas as pd

In [6]:
data_path = Dataset.get(
    dataset_project="ForeSightNEXT/Electric Load Forecasting",
    dataset_name="household-1235",
).get_local_copy()

data_path = Path(data_path, "power.csv")
resampled_data_path = Path("../data/resampled_power.csv")

In [3]:
data = pd.read_csv(
    data_path,
    # nrows=10000,
    usecols=["_time", "_value"],
    index_col="_time",
    parse_dates=True,
    date_format="ISO8601",
)
data.rename(columns={"_value": "power"}, inplace=True)
# data.index.name = "time"
data

                                  power
time
2020-07-28 14:01:02.030000+00:00    331
2020-07-28 14:01:04.791000+00:00    331
2020-07-28 14:01:07.733000+00:00    333
2020-07-28 14:01:10.752000+00:00    330
2020-07-28 14:01:13.731000+00:00    332
...                                 ...
2023-01-30 13:38:05.180000+00:00    440
2023-01-30 13:38:08.224000+00:00    437
2023-01-30 13:38:11.189000+00:00    448
2023-01-30 13:38:14.210000+00:00    440
2023-01-30 13:38:17.218000+00:00    438

[22425253 rows x 1 columns]

In [4]:
resampled_data = data.resample("15min").mean()
resampled_data

                                power
time
2020-07-28 14:00:00+00:00  300.014388
2020-07-28 14:15:00+00:00  251.965909
2020-07-28 14:30:00+00:00  289.356061
2020-07-28 14:45:00+00:00  230.844828
2020-07-28 15:00:00+00:00  270.125000
...                               ...
2023-01-30 12:30:00+00:00  750.270000
2023-01-30 12:45:00+00:00  403.076412
2023-01-30 13:00:00+00:00  465.383333
2023-01-30 13:15:00+00:00  371.170569
2023-01-30 13:30:00+00:00  364.843373

[87935 rows x 1 columns]

In [5]:
resampled_data.to_csv(resampled_data_path)